# =============================================================================
# CONCERN: Feasibility Check
# =============================================================================
# This concern validates that requirements depending on external systems,
# third-party APIs, or legacy integrations are actually feasible given the
# capabilities of those dependencies. Documents often assume capabilities
# that have not been verified against the actual dependency's limitations.
#
# WHY THIS MATTERS:
# A requirement that assumes a third-party API supports real-time webhooks
# when it only offers batch polling will fail during implementation. A
# feature that depends on a legacy system's REST API when the system only
# exposes SOAP will require unplanned adapter work. These feasibility gaps
# are discovered late, causing schedule slips, scope changes, and sometimes
# project failure.
#
# TYPICAL MANIFESTATION:
# - FRD assumes "real-time inventory sync from ERP" but ERP only supports
#   nightly batch exports
# - BRD requires "SSO via Partner X" but Partner X doesn't support SAML/OIDC
# - FRD specifies "push notifications via SMS gateway" but the gateway
#   only supports pull-based message retrieval
# - ADD integrates with a legacy system assuming REST API that doesn't exist
# =============================================================================

concern:
  id: "feasibility-check"
  version: "1.0"
  name: "Feasibility Check"
  category: "promise-validation"
  severity: "warn"

  description: |
    Validates that requirements depending on external systems, third-party
    APIs, legacy integrations, or partner services are feasible given the
    actual capabilities of those dependencies. Every assumed capability
    should be verified in the architecture document - either confirmed
    through documentation, API specs, or explicitly flagged as a risk
    requiring validation.

# -----------------------------------------------------------------------------
# TRIGGERS: When to load this concern
# -----------------------------------------------------------------------------
triggers:
  any_of:
    - external-api
    - third-party
    - integration
    - legacy-system

# -----------------------------------------------------------------------------
# EVALUATION: The reasoning task
# -----------------------------------------------------------------------------
evaluation:
  question: |
    Identify all external dependencies and third-party integrations, find
    requirements that depend on them, and check whether the architecture
    confirms the assumed capabilities actually exist.

    STEP 1: IDENTIFY EXTERNAL DEPENDENCIES AND THIRD-PARTY INTEGRATIONS
    Scan all documents for references to external systems:

    a) Third-Party APIs and Services
       - Payment processors (Stripe, PayPal, Adyen)
       - Identity providers (Auth0, Okta, Azure AD)
       - Communication services (Twilio, SendGrid, Firebase)
       - Cloud services (AWS, GCP, Azure managed services)
       - Look for: API, integration, third-party, vendor, provider, SaaS

    b) Legacy Systems
       - Enterprise systems (ERP, CRM, HR systems)
       - Mainframe or COBOL systems
       - On-premise databases
       - Internal systems with limited APIs
       - Look for: legacy, mainframe, on-premise, existing system, migration

    c) Partner and B2B Integrations
       - Partner APIs and data feeds
       - EDI or file-based integrations
       - Shared databases or data warehouses
       - Look for: partner, B2B, feed, EDI, exchange

    d) Infrastructure Dependencies
       - DNS providers, CDN services
       - Certificate authorities
       - Secret management services
       - Monitoring and logging platforms
       - Look for: infrastructure, DNS, CDN, certificate, monitoring

    For each dependency, capture:
    - Name and type
    - What documents reference it
    - What role it plays in the system

    STEP 2: FIND REQUIREMENTS THAT DEPEND ON EACH EXTERNAL SYSTEM
    For each identified dependency, find all requirements and features
    that assume its capabilities:

    a) Capability Assumptions
       - What operations does the requirement assume the dependency supports?
       - What data formats are assumed (REST, SOAP, GraphQL, batch, streaming)?
       - What communication patterns are assumed (sync, async, webhooks, polling)?
       - What throughput or latency is assumed?

    b) Feature Dependencies
       - Which FRD features directly depend on this external system?
       - Are there fallback features if the dependency is unavailable?
       - Is the dependency on the critical path for core functionality?

    c) Data Assumptions
       - What data is assumed to be available from the dependency?
       - What data freshness is assumed (real-time, near-real-time, batch)?
       - What data format and schema is assumed?

    STEP 3: CHECK IF ADD CONFIRMS CAPABILITY EXISTS
    For each assumed capability, search the ADD for confirmation:

    a) Explicit Confirmation
       - Does the ADD reference the dependency's documentation or API spec?
       - Does the ADD describe the integration pattern based on actual capabilities?
       - Are there proof-of-concept results or spike findings documented?
       - Look for: "verified", "confirmed", "tested", "POC", "spike"

    b) Implicit Confirmation
       - Does the ADD describe an integration pattern consistent with the
         dependency's known capabilities?
       - Does the architecture account for the dependency's limitations?

    c) No Confirmation
       - Does the ADD simply repeat the requirement's assumption without
         verifying it?
       - Is the integration described without referencing the dependency's
         actual API or documentation?
       - Are there phrases like "assumes", "expected to support", "TBD"?

    d) Contradiction
       - Does the ADD describe the dependency differently from the requirement?
       - Does the ADD mention limitations that conflict with the requirement?
       - Are there known constraints that make the requirement infeasible?

    STEP 4: FLAG ASSUMPTIONS WITHOUT VERIFICATION
    For each assumed capability, determine:
    - "verified": ADD confirms the capability based on actual dependency specs
    - "assumed": Requirement assumes capability but ADD doesn't verify it
    - "contradicted": ADD or known constraints indicate the capability
      doesn't exist or works differently than assumed

    Pay special attention to:
    - Real-time assumptions about batch-only systems
    - Push/webhook assumptions about pull-only APIs
    - Data format assumptions (JSON assumed but only XML available)
    - Rate limit assumptions (high throughput assumed but API has strict limits)
    - Authentication assumptions (OAuth assumed but only API key supported)
    - Data availability assumptions (fields assumed but not in actual API response)

  checklist:
    - id: "dependency-inventory"
      question: "Are all external dependencies and third-party integrations identified?"
    - id: "capability-verification"
      question: "Is each assumed capability verified against the dependency's actual documentation or API spec?"
    - id: "integration-pattern-match"
      question: "Do integration patterns (sync/async, push/pull) match the dependency's actual capabilities?"
    - id: "data-format-match"
      question: "Do assumed data formats and schemas match what the dependency actually provides?"
    - id: "risk-flagging"
      question: "Are unverified assumptions explicitly flagged as risks requiring validation?"

  evidence_required:
    - field: "requirement_text"
      type: "string"
      description: "The requirement or feature that depends on the external system (e.g., 'Real-time inventory sync from SAP ERP')"
      required: true

    - field: "requirement_source"
      type: "string"
      description: "Document and section where the requirement is stated (e.g., 'FRD Section 3.4 - Inventory Management')"
      required: true

    - field: "dependency_name"
      type: "string"
      description: "Name of the external dependency (e.g., 'SAP ERP', 'Stripe API', 'Legacy OrderDB')"
      required: true

    - field: "assumed_capability"
      type: "string"
      description: "What capability the requirement assumes the dependency has (e.g., 'Real-time webhook notifications on inventory changes')"
      required: true

    - field: "capability_verified"
      type: "boolean"
      description: "Whether the ADD confirms this capability exists based on actual dependency documentation or testing"
      required: true

    - field: "verification_source"
      type: "string | null"
      description: "Where in the ADD the capability is confirmed or contradicted (e.g., 'ADD Section 5.2 - SAP Integration, references SAP IDoc documentation')"
      required: true

    - field: "feasibility_status"
      type: "enum"
      values:
        - "verified"      # ADD confirms capability based on actual dependency specs
        - "assumed"        # Requirement assumes capability, ADD doesn't verify
        - "contradicted"  # ADD or known constraints indicate capability doesn't exist
      description: "Whether the assumed capability has been verified as feasible"
      required: true

    - field: "risk_detail"
      type: "string | null"
      description: "If not verified, explain the risk (e.g., 'SAP ERP only supports batch IDoc exports, not real-time webhooks. Integration would require polling or middleware.')"
      required: true

    - field: "confidence"
      type: "enum"
      values: ["high", "medium", "low"]
      description: "Confidence in the feasibility assessment"
      required: true

  failure_condition: |
    Report as ERROR when:

    1. feasibility_status is "contradicted" - the architecture or known
       dependency constraints indicate the assumed capability does not exist
       or works fundamentally differently than assumed. Examples:
       - Requirement assumes real-time webhooks but dependency only supports
         batch polling
       - Requirement assumes REST API but dependency only exposes SOAP/XML
       - Requirement assumes specific data fields but dependency doesn't
         include them in its response
       - Requirement assumes unlimited API calls but dependency has strict
         rate limits that would be exceeded

    2. A core business feature depends entirely on an unverified capability
       of a single external dependency with no fallback plan.

    3. The ADD describes an integration pattern that is incompatible with
       the dependency's known limitations (e.g., synchronous calls to a
       system documented as batch-only).

    Report as WARNING when:

    1. feasibility_status is "assumed" - the capability has not been
       verified. The requirement may or may not be feasible, but the
       risk has not been assessed.

    2. The ADD mentions the dependency but uses vague language like
       "will integrate with" or "expected to support" without referencing
       actual documentation or API specs.

    3. Multiple requirements depend on the same unverified external
       system, creating concentrated risk.

    4. The dependency is a legacy system with no public API documentation,
       and the integration approach is not validated through a POC or spike.

    5. Rate limits, authentication methods, or data formats are assumed
       but not explicitly confirmed.

  recommendation_template: |
    ## Gap: Unverified Dependency Capability

    **Requirement:** {requirement_text}
    **Source:** {requirement_source}
    **Dependency:** {dependency_name}
    **Assumed Capability:** {assumed_capability}
    **Status:** {feasibility_status}

    ### Risk Detail
    {risk_detail}

    ### Resolution Options

    1. **Verify Capability** (recommended):
       Consult the dependency's official documentation, API reference,
       or support team to confirm the assumed capability exists and
       works as expected. Document the findings in the ADD.

    2. **Conduct a Spike/POC**:
       Build a minimal proof of concept to validate the integration
       before committing to the approach in the architecture.

    3. **Design Fallback**:
       If the capability cannot be verified, design an alternative
       approach (e.g., polling instead of webhooks, adapter layer
       for format translation) and document it in the ADD.

    4. **Flag as Risk**:
       If verification is not possible before design approval,
       explicitly flag this as a risk in the ADD with a mitigation
       plan and timeline for validation.

    ### Why This Matters
    Unverified assumptions about external dependencies are among the
    top causes of project delays and scope changes. Discovering that
    a third-party API doesn't support an assumed capability during
    implementation forces redesign under time pressure.

# -----------------------------------------------------------------------------
# EXAMPLES
# -----------------------------------------------------------------------------
examples:
  well_documented:
    - source: "FRD Section 3.4 / ADD Section 5.2"
      text: |
        "FRD: 'The system shall display real-time inventory levels
        synchronized from the SAP ERP system.'
        ADD: 'SAP integration uses IDoc-based batch exports (SAP does not
        support real-time webhooks). A polling adapter runs every 5 minutes,
        fetching inventory changes via RFC/BAPI calls. Near-real-time
        achieved through 5-minute cache with invalidation on poll.
        Verified against SAP S/4HANA API documentation v2.0.
        Spike results: https://wiki.internal/spikes/sap-inventory-poc'"
      assessment: |
        requirement_text: "Real-time inventory levels from SAP ERP"
        dependency_name: "SAP ERP (S/4HANA)"
        assumed_capability: "Real-time inventory sync"
        capability_verified: true
        feasibility_status: "verified"
        risk_detail: null
        note: "ADD acknowledges SAP limitation and designs around it with polling adapter. Spike validates the approach."

  contradicted_assumption:
    - source: "FRD Section 4.1 / ADD Section 3.3"
      text: |
        "FRD: 'When a new order is placed, the legacy OrderDB shall push
        a real-time notification to the new system via webhook.'
        ADD: 'The legacy OrderDB is a DB2 mainframe database accessed
        via CICS transactions. No outbound API or webhook capability.'"
      assessment: |
        requirement_text: "Real-time webhook notification from legacy OrderDB"
        dependency_name: "Legacy OrderDB (DB2/CICS)"
        assumed_capability: "Outbound webhook notifications on new orders"
        capability_verified: false
        feasibility_status: "contradicted"
        risk_detail: "The legacy DB2/CICS system has no outbound webhook
                      capability. The FRD assumes push-based notifications
                      but the system can only be queried via CICS transactions.
                      Integration requires a CDC (Change Data Capture) solution
                      or polling adapter, neither of which is documented."

  unverified_assumption:
    - source: "BRD Section 2.3 / ADD Section 4.1"
      text: |
        "BRD: 'The platform shall support SSO via Partner X's identity
        provider for all B2B users.'
        ADD: 'B2B authentication will integrate with Partner X's IdP
        using SAML 2.0 for single sign-on.'"
      assessment: |
        requirement_text: "SSO via Partner X's identity provider"
        dependency_name: "Partner X Identity Provider"
        assumed_capability: "SAML 2.0 SSO support"
        capability_verified: false
        feasibility_status: "assumed"
        risk_detail: "ADD describes SAML 2.0 integration but does not
                      reference Partner X's actual IdP documentation or
                      confirm SAML support. Partner X may only support
                      OIDC, proprietary federation, or may require custom
                      integration. No POC or partner confirmation documented."

# -----------------------------------------------------------------------------
# METADATA
# -----------------------------------------------------------------------------
metadata:
  created: "2026-02"
  last_updated: "2026-02"
  author: "doc-lint v0.2"
  related_concerns:
    - "api-contract-consistency"     # external API contracts must be verified
    - "resilience-triad"             # external dependencies need resilience mechanisms
    - "horizontal-traceability"      # dependency-based requirements need traceability
    - "sla-architecture-alignment"   # dependency SLAs affect system SLAs
  references:
    - "TOGAF - Architecture Requirements Management"
    - "IEEE 1471 - Architecture Description of Software-Intensive Systems"
    - "Thoughtworks Tech Radar - Dependency Management Practices"
    - "Building Evolutionary Architectures (Ford, Parsons, Kua) - Fitness Functions"
