# =============================================================================
# CONCERN: SLA-Architecture Alignment
# =============================================================================
# This concern validates that Service Level Agreement (SLA) promises made in
# business and functional documents are actually supported by the architecture
# described in technical design documents. An SLA is a promise to customers
# or stakeholders - if the architecture cannot deliver it, the promise is
# already broken before a single line of code is written.
#
# WHY THIS MATTERS:
# SLA breaches have direct financial and reputational consequences. When a
# BRD promises 99.99% uptime but the ADD describes a single-region deployment
# with no failover, that promise is structurally impossible to keep. Catching
# these misalignments during documentation review prevents expensive
# post-launch redesigns and contractual penalties.
#
# TYPICAL MANIFESTATION:
# - BRD promises 99.99% uptime but ADD shows single-region, single-AZ deployment
# - FRD specifies <200ms API response time but ADD uses synchronous chain of 5 services
# - BRD guarantees <1 hour RTO but ADD has no disaster recovery plan
# - SLA promises 24/7 availability but ADD describes maintenance windows
# =============================================================================

concern:
  id: "sla-architecture-alignment"
  version: "1.0"
  name: "SLA-Architecture Alignment"
  category: "promise-validation"
  severity: "error"

  description: |
    Validates that every SLA/SLO promise found in business and functional
    documents (BRD, FRD) has corresponding architectural support in
    technical documents (ADD, TSD). This includes availability targets,
    latency requirements, throughput guarantees, recovery objectives
    (RTO/RPO), and durability commitments. The architecture must
    demonstrably support each promise, not just acknowledge it.

# -----------------------------------------------------------------------------
# TRIGGERS: When to load this concern
# -----------------------------------------------------------------------------
triggers:
  any_of:
    - sla
    - availability
    - performance
    - uptime

# -----------------------------------------------------------------------------
# EVALUATION: The reasoning task
# -----------------------------------------------------------------------------
evaluation:
  question: |
    Extract all SLA and SLO promises from business/functional documents,
    then verify that the architecture can actually deliver each promise.

    STEP 1: EXTRACT ALL SLA/SLO PROMISES FROM BRD AND FRD
    Scan BRD and FRD for quantitative and qualitative commitments:

    a) Availability and Uptime
       - Uptime percentages (99.9%, 99.99%, 99.999%)
       - Availability windows (24/7, business hours only)
       - Planned maintenance allowances
       - Look for: uptime, availability, SLA, "nines"

    b) Latency and Response Time
       - API response time targets (p50, p95, p99)
       - End-to-end latency requirements
       - Page load time commitments
       - Look for: latency, response time, milliseconds, performance

    c) Throughput and Capacity
       - Requests per second targets
       - Concurrent user commitments
       - Data processing volume guarantees
       - Look for: throughput, TPS, RPS, concurrent, capacity

    d) Recovery Objectives
       - Recovery Time Objective (RTO): max downtime after failure
       - Recovery Point Objective (RPO): max data loss window
       - Disaster recovery commitments
       - Look for: RTO, RPO, recovery, disaster, backup, failover

    e) Durability and Data Guarantees
       - Data durability promises (e.g., "no data loss")
       - Backup and retention commitments
       - Consistency guarantees
       - Look for: durability, backup, retention, consistency

    For each promise, capture:
    - The exact claim with its metric and target value
    - The source document and section
    - Whether it is contractual (SLA) or internal (SLO)

    STEP 2: FOR EACH PROMISE, FIND ARCHITECTURAL SUPPORT IN ADD
    For each extracted SLA/SLO promise, search the ADD for mechanisms
    that enable it:

    a) For availability promises:
       - Multi-region or multi-AZ deployment?
       - Active-active or active-passive failover?
       - Health checks and automatic recovery?
       - Load balancing and redundancy?
       - Calculate theoretical max availability from architecture

    b) For latency promises:
       - What is the call chain depth? (each hop adds latency)
       - Are calls synchronous or asynchronous?
       - Is caching documented?
       - Are there known bottlenecks (shared databases, sequential processing)?
       - Can the architecture physically deliver the promised latency?

    c) For throughput promises:
       - Horizontal scaling mechanisms?
       - Connection pooling and resource limits?
       - Rate limiting and backpressure?
       - Database sharding or read replicas?

    d) For recovery promises:
       - Backup frequency vs RPO target?
       - Failover automation vs RTO target?
       - Disaster recovery runbooks?
       - Cross-region replication?

    e) For durability promises:
       - Storage replication strategy?
       - Write-ahead logging?
       - Multi-region data replication?
       - Backup verification and testing?

    STEP 3: ASSESS WHETHER ARCHITECTURE CAN DELIVER THE PROMISE
    For each SLA/SLO promise, determine:
    - Does the architecture explicitly support it? (supported)
    - Does the architecture contradict it? (unsupported)
    - Is there partial support with gaps? (partial)
    - Is the architecture silent on this? (unclear)

    Apply domain knowledge:
    - 99.99% uptime (52 min/year downtime) typically requires
      multi-AZ + auto-failover + zero-downtime deploys
    - <200ms p99 latency is incompatible with 5-hop synchronous chains
    - <1 hour RTO requires automated failover, not manual runbooks
    - 99.999999999% durability requires cross-region replication

  checklist:
    - id: "availability-support"
      question: "Does the architecture support the promised availability/uptime target?"
    - id: "latency-support"
      question: "Can the architecture deliver the promised latency targets given the call chain?"
    - id: "throughput-support"
      question: "Does the architecture have scaling mechanisms for the promised throughput?"
    - id: "recovery-support"
      question: "Do backup and failover mechanisms meet the promised RTO/RPO?"
    - id: "durability-support"
      question: "Does the storage and replication strategy support the promised durability?"
    - id: "no-contradictions"
      question: "Are there any architectural decisions that directly contradict an SLA promise?"

  evidence_required:
    - field: "sla_promise"
      type: "string"
      description: "The exact SLA/SLO claim (e.g., '99.99% uptime', '<200ms p99 latency', 'RTO < 1 hour')"
      required: true

    - field: "sla_source"
      type: "string"
      description: "Document and section where the promise is made (e.g., 'BRD Section 5.1 - SLA Requirements')"
      required: true

    - field: "sla_metric"
      type: "string"
      description: "The type of metric (e.g., 'availability', 'latency', 'throughput', 'RTO', 'RPO', 'durability')"
      required: true

    - field: "sla_target"
      type: "string"
      description: "The quantitative target value (e.g., '99.99%', '<200ms', '10,000 RPS', '<1 hour')"
      required: true

    - field: "architectural_support"
      type: "string | null"
      description: "What architectural mechanisms support this promise (e.g., 'Multi-AZ deployment with auto-failover, ALB health checks')"
      required: true

    - field: "architecture_source"
      type: "string | null"
      description: "Where in the ADD the supporting architecture is described (e.g., 'ADD Section 4.2 - Deployment Architecture')"
      required: true

    - field: "alignment_status"
      type: "enum"
      values:
        - "supported"      # Architecture clearly supports the promise
        - "unsupported"    # Architecture cannot deliver the promise
        - "partial"        # Some support exists but gaps remain
        - "unclear"        # Architecture is silent on this promise
      description: "Whether the architecture can deliver the SLA promise"
      required: true

    - field: "gap_detail"
      type: "string | null"
      description: "If not 'supported', explain why the architecture falls short (e.g., 'Single-region deployment cannot achieve 99.99% uptime target')"
      required: true

    - field: "confidence"
      type: "enum"
      values: ["high", "medium", "low"]
      description: "Confidence in the alignment assessment"
      required: true

  failure_condition: |
    Report as ERROR when:

    1. alignment_status is "unsupported" - the architecture structurally
       cannot deliver the SLA promise. Examples:
       - 99.99% uptime promised but single-region, single-AZ deployment
       - <200ms latency promised but synchronous 5-hop call chain
       - <1 hour RTO but only manual recovery procedures documented
       - "No data loss" promised but no replication or WAL documented

    2. alignment_status is "unclear" for a contractual SLA (not internal
       SLO) - a binding promise has no architectural backing at all.

    3. Architecture explicitly contradicts the promise (e.g., ADD
       describes scheduled maintenance windows but BRD promises 24/7
       availability with no maintenance window).

    4. Recovery objectives (RTO/RPO) are promised but ADD has no
       disaster recovery or backup strategy documented.

    Report as WARNING when:

    1. alignment_status is "partial" - architecture partially supports
       the promise but has identifiable gaps that may cause breaches.

    2. alignment_status is "unclear" for internal SLOs - not contractual
       but still represents team intent that should be validated.

    3. SLA promise exists but the target value seems unrealistic for
       the described architecture (e.g., 99.999% uptime with a
       traditional relational database as the single data store).

    4. Architecture supports the promise but with no margin - a single
       component failure would breach the SLA.

  recommendation_template: |
    ## Gap: SLA Promise Not Supported by Architecture

    **SLA Promise:** {sla_promise}
    **Target:** {sla_target}
    **Source:** {sla_source}
    **Architecture Source:** {architecture_source}
    **Alignment Status:** {alignment_status}

    ### Gap Detail
    {gap_detail}

    ### Resolution Options

    1. **Upgrade Architecture** (if SLA is correct):
       Enhance the architecture to support the promised SLA. This may
       require multi-region deployment, redundancy, caching layers,
       or automated failover mechanisms.

    2. **Revise SLA Target** (if architecture is correct):
       Adjust the SLA promise to match what the architecture can
       realistically deliver. Communicate the revised target to
       stakeholders before it becomes contractual.

    3. **Document Constraints** (if trade-off is intentional):
       If the gap is a known trade-off (cost vs. availability),
       document it explicitly so stakeholders can make an informed
       decision.

    ### Why This Matters
    SLA breaches often have financial penalties, reputational damage,
    and customer churn. Catching misalignment during design review
    is orders of magnitude cheaper than discovering it in production.

# -----------------------------------------------------------------------------
# EXAMPLES
# -----------------------------------------------------------------------------
examples:
  well_documented:
    - source: "BRD Section 5.1 / ADD Section 4.2"
      text: |
        "BRD: 'The platform shall maintain 99.99% availability (52.6 min/year
        maximum downtime).'
        ADD: 'Deployed across 3 AWS Availability Zones with Application Load
        Balancer, auto-scaling groups, and automated failover. RDS Multi-AZ
        with automatic failover. Blue-green deployments for zero-downtime
        releases. Health checks every 10s with automatic instance replacement.'"
      assessment: |
        sla_promise: "99.99% availability"
        sla_target: "99.99%"
        sla_metric: "availability"
        architectural_support: "Multi-AZ (3), ALB, auto-scaling, RDS Multi-AZ, blue-green deploys"
        alignment_status: "supported"
        gap_detail: null
        confidence: "high"

  unsupported_promise:
    - source: "BRD Section 5.1 / ADD Section 3.1"
      text: |
        "BRD: 'The system guarantees 99.99% uptime for all API endpoints.'
        ADD: 'The application is deployed on a single EC2 instance in
        us-east-1a with a PostgreSQL database on the same instance.
        Backups are taken nightly to S3.'"
      assessment: |
        sla_promise: "99.99% uptime"
        sla_target: "99.99%"
        sla_metric: "availability"
        architectural_support: "Single EC2 instance, single AZ, co-located database"
        alignment_status: "unsupported"
        gap_detail: "Single-instance, single-AZ deployment has no redundancy.
                     Any instance failure, AZ outage, or deployment causes
                     downtime. Theoretical max availability is ~99.5% at best.
                     99.99% requires multi-AZ with auto-failover at minimum."
        confidence: "high"

  latency_contradiction:
    - source: "FRD Section 3.2 / ADD Section 5.3"
      text: |
        "FRD: 'API responses must complete within 200ms at the 99th percentile.'
        ADD: 'The order creation flow involves: API Gateway -> AuthService ->
        OrderService -> InventoryService -> PaymentService -> NotificationService.
        All calls are synchronous REST.'"
      assessment: |
        sla_promise: "<200ms p99 latency"
        sla_target: "<200ms"
        sla_metric: "latency"
        architectural_support: "Synchronous chain of 6 services"
        alignment_status: "unsupported"
        gap_detail: "A synchronous chain of 6 services, each adding network
                     latency plus processing time, makes <200ms p99 extremely
                     unlikely. At 30ms per hop, the chain alone is ~180ms
                     before any business logic. Spikes in any single service
                     will breach the target."
        confidence: "high"

# -----------------------------------------------------------------------------
# METADATA
# -----------------------------------------------------------------------------
metadata:
  created: "2026-02"
  last_updated: "2026-02"
  author: "doc-lint v0.2"
  related_concerns:
    - "resilience-triad"             # resilience mechanisms directly affect SLA delivery
    - "failure-domain-isolation"     # isolation boundaries affect blast radius and uptime
    - "scalability-claim-validation" # scalability affects throughput SLAs
    - "horizontal-traceability"      # SLA promises are BRD requirements that need tracing
  references:
    - "Google SRE Book: Service Level Objectives"
    - "AWS Well-Architected: Reliability Pillar - Availability"
    - "Azure Architecture: SLA Estimation for Multi-Tier Applications"
    - "The Art of SLOs - Google Cloud"
