import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";

import { buildBootstrapDocs, writeBootstrapDocs, computeDocumentationGaps } from "../../src/core/bootstrap.js";
import { buildCodeMap } from "../../src/core/code-scan.js";
import { loadAllConcerns } from "../../src/core/concerns.js";
import { matchConcerns } from "../../src/core/signals.js";

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "doc-lint-bootstrap-"));
  fs.mkdirSync(path.join(tmpDir, "src"), { recursive: true });
  fs.writeFileSync(
    path.join(tmpDir, "src/server.ts"),
    "const app = express();\napp.post('/charge', h);\nconst s = new Stripe(process.env.STRIPE_KEY);",
  );
  fs.writeFileSync(
    path.join(tmpDir, "package.json"),
    JSON.stringify({ name: "shop", dependencies: { express: "^4", stripe: "^14" } }),
  );
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

async function setup(signals: string[]) {
  const codeMap = await buildCodeMap(tmpDir);
  const { matched } = matchConcerns(signals, loadAllConcerns());
  return { codeMap, matched };
}

describe("buildBootstrapDocs", () => {
  it("produces the four evidence-named scaffolds", async () => {
    const { codeMap, matched } = await setup(["payments", "rest-api"]);
    const docs = buildBootstrapDocs(codeMap, ["payments", "rest-api"], matched);
    expect(docs.map((d) => d.name)).toEqual([
      "architecture-as-built.md",
      "functional-surface.md",
      "operations-surface.md",
      "doc-todos.md",
    ]);
  });

  it("fills architecture facts from the code map and leaves intent as TODOs", async () => {
    const { codeMap, matched } = await setup(["payments", "rest-api"]);
    const arch = buildBootstrapDocs(codeMap, ["payments", "rest-api"], matched).find(
      (d) => d.name === "architecture-as-built.md",
    )!;
    expect(arch.content).toContain("POST"); // route fact
    expect(arch.content).toContain("/charge");
    expect(arch.content).toContain("express"); // dependency fact
    expect(arch.content).toContain("STRIPE_KEY"); // env fact
    expect(arch.content).toContain("TODO (human intent)"); // intent left to human
    expect(arch.content).toContain("GENERATED by doc-lint bootstrap"); // honesty banner
  });

  it("doc-todos lists applicable concerns as a gap inventory grouped by category", async () => {
    const { codeMap, matched } = await setup(["payments", "rest-api", "external-api"]);
    const todos = buildBootstrapDocs(codeMap, ["payments", "rest-api", "external-api"], matched).find(
      (d) => d.name === "doc-todos.md",
    )!;
    expect(todos.content).toContain("Gap Inventory");
    // a triggered core concern should appear with its trigger signal
    expect(todos.content).toContain("Resilience Triad");
    expect(todos.content).toMatch(/triggered by:.*external-api/);
  });

  it("is honest when the code map has no models (no ORM detected)", async () => {
    const { codeMap, matched } = await setup(["rest-api"]);
    const arch = buildBootstrapDocs(codeMap, ["rest-api"], matched).find((d) => d.name === "architecture-as-built.md")!;
    expect(arch.content).toContain("No ORM models statically detected");
  });
});

describe("computeDocumentationGaps", () => {
  it("maps each matched concern to a gap with its triggering signals", async () => {
    const { matched } = await setup(["payments", "rest-api"]);
    const gaps = computeDocumentationGaps(matched, ["payments", "rest-api"]);
    expect(gaps.length).toBe(matched.length);
    for (const g of gaps) {
      expect(g.concernId).toBeTruthy();
      // every gap was triggered by at least one declared signal
      expect(g.triggeredBy.length).toBeGreaterThan(0);
    }
  });
});

describe("writeBootstrapDocs", () => {
  it("writes the scaffolds under the out dir", async () => {
    const { codeMap, matched } = await setup(["rest-api"]);
    const docs = buildBootstrapDocs(codeMap, ["rest-api"], matched);
    const written = writeBootstrapDocs(docs, tmpDir, ".doc-lint/bootstrap");
    expect(written).toHaveLength(4);
    expect(fs.existsSync(path.join(tmpDir, ".doc-lint/bootstrap/architecture-as-built.md"))).toBe(true);
    expect(fs.existsSync(path.join(tmpDir, ".doc-lint/bootstrap/doc-todos.md"))).toBe(true);
  });

  it("refuses to write outside the project (path traversal)", async () => {
    const { codeMap, matched } = await setup(["rest-api"]);
    const docs = buildBootstrapDocs(codeMap, ["rest-api"], matched);
    expect(() => writeBootstrapDocs(docs, tmpDir, "../../escape")).toThrow(/inside the project/i);
    expect(() => writeBootstrapDocs(docs, tmpDir, "/tmp/abs")).toThrow(/inside the project/i);
  });
});
