# =============================================================================
# CONCERN: Cost & Budget Enforcement
# =============================================================================
# This concern validates that every metered or auto-scaling resource has
# documented budget caps and cost attribution. Without explicit cost controls,
# scaling events, runaway queries, or misconfigured resources can generate
# unbounded cloud bills before anyone notices.
#
# WHY THIS MATTERS:
# Cloud cost overruns are one of the most common operational surprises. A single
# misconfigured auto-scaling policy, an unthrottled batch job, or a forgotten
# dev environment can generate thousands in unexpected charges. Budget caps and
# cost attribution ensure that spending is visible, bounded, and traceable to
# the team or service responsible.
# =============================================================================

concern:
  id: "cost-budget-enforcement"
  version: "1.0"
  name: "Cost & Budget Enforcement"
  category: "operational"
  severity: "warn"

  description: |
    Every metered or scaling resource must document budget caps and cost
    attribution. This includes auto-scaling groups, serverless functions,
    managed databases, CDN bandwidth, API gateway usage, and any resource
    where consumption directly drives cost. Each resource must have:
    1. A documented budget cap or spending limit
    2. Cost attribution to a team, service, or cost center
    3. Defined behavior when budget is exceeded
    4. Observability into current spend vs. budget

# -----------------------------------------------------------------------------
# TRIGGERS: When to load this concern
# -----------------------------------------------------------------------------
triggers:
  any_of:
    - cost-management
    - auto-scaling
    - quotas

  escalate_if:
    - payments

# -----------------------------------------------------------------------------
# EVALUATION: The reasoning task
# -----------------------------------------------------------------------------
evaluation:
  question: |
    Systematically identify every metered or scaling resource in the documented
    system, then evaluate whether budget caps and cost attribution are documented.

    STEP 1: IDENTIFY METERED/SCALING RESOURCES
    Scan all documents for resources where usage drives cost:
    - Auto-scaling groups (EC2, ECS, Kubernetes HPA)
    - Serverless functions (Lambda, Cloud Functions)
    - Managed databases (RDS, DynamoDB, Cloud SQL)
    - Message queues and streaming (SQS, Kafka, Kinesis)
    - CDN and bandwidth (CloudFront, Fastly)
    - API gateways and load balancers
    - Storage (S3, GCS, blob storage)
    - Third-party API usage (Stripe, Twilio, SendGrid)

    STEP 2: FOR EACH RESOURCE, CHECK BUDGET DOCUMENTATION
    a) Is there a documented budget cap or spending limit?
       - Hard cap (service stops/throttles at limit)
       - Soft cap (alert fires but service continues)
       - No cap documented
    b) What mechanism enforces the budget?
       - Cloud provider budget alerts (AWS Budgets, GCP Billing Alerts)
       - Application-level throttling
       - Quota enforcement
       - Manual monitoring
    c) Is cost attribution documented?
       - Tagged to a team, service, or cost center?
       - Can spending be traced to the responsible owner?
    d) What happens when budget is exceeded?
       - Service degrades gracefully?
       - Hard stop?
       - Alert only?
       - Undefined?

    STEP 3: CHECK OBSERVABILITY
    For each resource:
    - Is current spend visible in dashboards or reports?
    - Are there alerts for approaching budget thresholds?
    - Is spend trending tracked over time?

    STEP 4: FLAG GAPS
    Any metered resource without a documented budget cap, cost attribution,
    or exceed behavior is a gap.

  checklist:
    - id: "resource-inventory"
      question: "Are all metered/scaling resources identified with their cost drivers?"
    - id: "budget-caps"
      question: "Does each resource have a documented budget cap or spending limit?"
    - id: "cost-attribution"
      question: "Is each resource attributed to a team, service, or cost center?"
    - id: "exceed-behavior"
      question: "Is the behavior when budget is exceeded documented for each resource?"
    - id: "spend-observability"
      question: "Is current spend vs. budget visible through dashboards or alerts?"

  evidence_required:
    - field: "resource_name"
      type: "string"
      description: "Name of the metered/scaling resource (e.g., 'OrderService auto-scaling group', 'Lambda: processPayments', 'DynamoDB orders table')"
      required: true

    - field: "budget_documented"
      type: "boolean"
      description: "Whether a budget cap or spending limit is documented for this resource"
      required: true

    - field: "budget_mechanism"
      type: "string | null"
      description: "The mechanism enforcing the budget (e.g., 'AWS Budget alert at $500/mo', 'Application-level rate limit', 'DynamoDB provisioned capacity')"
      required: true

    - field: "cost_attribution_documented"
      type: "boolean"
      description: "Whether the resource is attributed to a team, service, or cost center"
      required: true

    - field: "exceed_behavior"
      type: "string | null"
      description: "What happens when budget is exceeded (e.g., 'Throttle to baseline capacity', 'Alert on-call, no auto-stop', 'Hard limit via quota')"
      required: true

    - field: "observability_documented"
      type: "boolean"
      description: "Whether current spend vs. budget is visible through dashboards or alerts"
      required: true

    - field: "source_location"
      type: "string"
      description: "Where this resource is documented (e.g., 'ADD Section 6.1 - Infrastructure')"
      required: true

    - field: "confidence"
      type: "enum"
      values: ["high", "medium", "low"]
      description: "Your confidence that this assessment is accurate"
      required: true

  failure_condition: |
    Report as ERROR when ANY of the following are true:

    1. An auto-scaling resource has budget_documented = FALSE - unbounded
       scaling without a budget cap can generate unlimited costs

    2. A payment-adjacent resource (payment processing, billing) has
       cost_attribution_documented = FALSE - financial resources must be
       traceable to responsible owners

    Report as WARNING when:

    1. budget_documented = FALSE for any metered resource

    2. budget_documented = TRUE but exceed_behavior is NULL or undefined -
       a budget without enforcement is just an aspiration

    3. cost_attribution_documented = FALSE - spending cannot be traced
       to the responsible team

    4. observability_documented = FALSE - team cannot see current spend
       relative to budget

  recommendation_template: |
    ## Gap: {resource_name} - Missing Cost/Budget Documentation

    **Location:** {source_location}

    ### Required Documentation

    Add cost and budget documentation covering:

    1. **Budget Cap**
       - What is the monthly/daily spending limit for this resource?
       - Is it a hard cap (service stops) or soft cap (alert only)?
       - Example: "Auto-scaling group capped at 20 instances max.
         AWS Budget alert at $2,000/month with hard stop at $3,000."

    2. **Cost Attribution**
       - Which team or cost center owns this resource's spend?
       - How is the resource tagged for billing visibility?
       - Example: "Tagged with team=payments, service=order-processing,
         env=production. Monthly cost reviewed in payments team budget."

    3. **Exceed Behavior**
       - What happens when the budget is reached?
       - Example: "At 80% budget, alert fires to #cost-alerts. At 100%,
         auto-scaling is capped and requests queue. On-call reviews within 1h."

    4. **Observability**
       - Where can current spend be monitored?
       - Example: "Grafana dashboard: Cloud Costs > OrderService.
         Daily Slack digest to #payments-costs channel."

# -----------------------------------------------------------------------------
# EXAMPLES
# -----------------------------------------------------------------------------
examples:
  well_documented:
    - source: "ADD Section 6.1 - Infrastructure Costs"
      text: |
        "The OrderService auto-scaling group scales between 2-20 instances
        based on CPU utilization. Monthly budget: $3,000. AWS Budget alert
        at $2,400 (80%) notifies #infra-costs. At $3,000 hard cap, scaling
        is frozen and on-call is paged. Cost center: payments-team.
        Dashboard: Grafana > Cloud Costs > OrderService."
      assessment: |
        resource_name: "OrderService auto-scaling group"
        budget_documented: true
        budget_mechanism: "AWS Budget alert at $2,400, hard cap at $3,000"
        cost_attribution_documented: true
        exceed_behavior: "Scaling frozen, on-call paged"
        observability_documented: true
        confidence: "high"

  poorly_documented:
    - source: "ADD Section 5.2"
      text: |
        "The notification service uses Lambda functions triggered by SQS
        messages. Auto-scales based on queue depth."
      assessment: |
        resource_name: "Notification Lambda functions"
        budget_documented: false
        budget_mechanism: null
        cost_attribution_documented: false
        exceed_behavior: null
        observability_documented: false
        confidence: "high"
        gap: "Lambda scales based on queue depth with no documented budget
              cap, cost attribution, or exceed behavior. A burst of
              notifications could trigger thousands of concurrent invocations
              with unbounded cost."

# -----------------------------------------------------------------------------
# METADATA
# -----------------------------------------------------------------------------
metadata:
  created: "2026-02"
  last_updated: "2026-02"
  tier: 2
  author: "Multi-Expert Consensus (Claude, Gemini, Codex)"
  related_concerns:
    - "alerting-slo-alignment"
    - "scalability-claim-validation"
  references:
    - "AWS Well-Architected Framework - Cost Optimization Pillar"
    - "FinOps Foundation: https://www.finops.org/framework/"
