import * as fs from "node:fs";
import * as path from "node:path";

import { isConcernSchema, isInteractionSchema } from "../types/concerns.js";

import type { CodeMap, LoadedConcern } from "../types/index.js";

// a generated scaffold file (deterministic — no LLM).
export interface BootstrapDoc {
  name: string; // file name, e.g. "architecture-as-built.md"
  content: string;
}

// a single documentation gap: a concern that applies to the detected signals but
// has no authored documentation yet.
export interface DocumentationGap {
  concernId: string;
  name: string;
  category: string;
  severity: string;
  triggeredBy: string[]; // declared signals that activated this concern
  whatToDocument: string; // first line of the concern description
}

const BANNER =
  "<!-- GENERATED by doc-lint bootstrap from a static code scan.\n" +
  "     This is an AS-BUILT scaffold: facts come from the code, INTENT is left as TODOs.\n" +
  "     Code cannot tell you WHY — fill in the TODOs, then lint in doc-first or reconcile mode. -->\n\n";

function firstLine(text: string | undefined): string {
  if (!text) return "";
  return text.trim().split("\n")[0]!.trim();
}

// escape pipe so values don't break GitHub-flavored markdown table cells
function cell(value: string): string {
  return value.replace(/\|/g, "\\|");
}

function concernDescription(c: LoadedConcern): string {
  if (isConcernSchema(c.schema)) return firstLine(c.schema.concern.description);
  if (isInteractionSchema(c.schema)) return firstLine(c.schema.interaction.description);
  return "";
}

// which matched concerns lack documentation (in code-first, all of them do).
export function computeDocumentationGaps(
  matched: LoadedConcern[],
  declaredSignals: string[],
): DocumentationGap[] {
  const declared = new Set(declaredSignals);
  return matched.map((c) => ({
    concernId: c.id,
    name: c.name,
    category: c.category,
    severity: c.severity,
    triggeredBy: c.triggerSignals.filter((s) => declared.has(s)),
    whatToDocument: concernDescription(c),
  }));
}

// ─── evidence-named scaffolds ────────────────────────────────────────────────

function routesTable(codeMap: CodeMap): string {
  if (codeMap.routes.length === 0) return "_No HTTP routes statically detected._";
  const rows = codeMap.routes
    .map((r) => `| ${cell(r.method)} | \`${cell(r.path)}\` | ${cell(r.file)}:${r.line} |`)
    .join("\n");
  return `| Method | Path | Source |\n|--------|------|--------|\n${rows}`;
}

function modelsTable(codeMap: CodeMap): string {
  if (codeMap.models.length === 0) {
    return "_No ORM models statically detected (the scan recognizes Prisma/Mongoose/Drizzle/TypeORM only)._";
  }
  const rows = codeMap.models
    .map((m) => `| \`${cell(m.name)}\` | ${cell(m.orm)} | ${cell(m.file)}:${m.line} |`)
    .join("\n");
  return `| Entity | ORM | Source |\n|--------|-----|--------|\n${rows}`;
}

function depsList(codeMap: CodeMap): string {
  const deps = [...new Set(codeMap.packages.flatMap((p) => p.dependencies))];
  return deps.length > 0 ? deps.map((d) => `\`${d}\``).join(", ") : "_none detected_";
}

function externalCallsList(codeMap: CodeMap): string {
  if (codeMap.externalCalls.length === 0) return "_No external calls statically detected._";
  const items = [...new Set(codeMap.externalCalls.map((c) => `- ${c.target} [${c.kind}] (${c.file}:${c.line})`))];
  return items.join("\n");
}

function coverageNote(codeMap: CodeMap): string {
  const cov = codeMap.coverage;
  const lines = [
    `- Files: ${codeMap.fileCount} total, ${codeMap.sampledFiles} scanned.`,
  ];
  if (cov.unsupportedLanguages.length > 0) {
    lines.push(`- Not analyzed (unsupported): ${cov.unsupportedLanguages.join(", ")}.`);
  }
  lines.push(
    "- The scan is a sampled, regex-based view. Anything not listed was either absent OR not scanned — verify before treating absence as fact.",
  );
  return lines.join("\n");
}

function architectureDoc(codeMap: CodeMap): BootstrapDoc {
  const content = `${BANNER}# Architecture (As-Built)

> Facts below are extracted from a static code scan. Sections marked **TODO** require
> human authorship — they capture intent the code cannot express.

## System Overview

Detected dependencies: ${depsList(codeMap)}

> **TODO (intent):** What is this system *for*? Summarize the business purpose, the
> primary domains, and the key non-functional targets (availability, latency, scale).

## Components & Entrypoints

${codeMap.entrypoints.length > 0 ? codeMap.entrypoints.map((e) => `- ${e}`).join("\n") : "_No entrypoints detected._"}

\`\`\`
${codeMap.tree}
\`\`\`

## HTTP Surface

${routesTable(codeMap)}

## Data Model

${modelsTable(codeMap)}

## External Dependencies & Integrations

${externalCallsList(codeMap)}

## Configuration

Environment variables referenced in code: ${codeMap.envVars.length > 0 ? codeMap.envVars.map((e) => `\`${e}\``).join(", ") : "_none detected_"}

Infrastructure signals: ${codeMap.configSignals.length > 0 ? codeMap.configSignals.join(", ") : "_none detected_"}

## TODO (human intent)

- [ ] Rationale for key technology choices (and alternatives considered)
- [ ] Failure-domain boundaries and blast radius per component
- [ ] Resilience policy (timeouts, retries, circuit breakers) per external dependency
- [ ] State ownership and consistency model

## Coverage & Unknowns

${coverageNote(codeMap)}
`;
  return { name: "architecture-as-built.md", content };
}

function functionalDoc(codeMap: CodeMap): BootstrapDoc {
  const capabilities =
    codeMap.routes.length > 0
      ? codeMap.routes
          .map(
            (r) =>
              `### ${r.method} \`${r.path}\`\n\n_Source: ${r.file}:${r.line}_\n\n` +
              `> **TODO:** describe the behavior, inputs/outputs, validation, error responses, ` +
              `and acceptance criteria. The code shows the route exists; it cannot state the contract.`,
          )
          .join("\n\n")
      : "_No HTTP capabilities statically detected._";

  const content = `${BANNER}# Functional Surface (As-Built)

> The capabilities below are derived from statically-detected routes/jobs. Behavior,
> contracts, and acceptance criteria are **TODO** — code shows *that* something exists,
> not *what it promises*.

## Capabilities

${capabilities}

## Exported API Surface

${
  codeMap.apiSurface.length > 0
    ? codeMap.apiSurface.slice(0, 100).map((a) => `- \`${a.kind} ${a.name}\` (${a.file}:${a.line})`).join("\n")
    : "_No exported surface detected._"
}

## TODO (human intent)

- [ ] Business rules and invariants per capability
- [ ] Acceptance criteria / definition of done
- [ ] User goals and the "why" behind each capability
- [ ] Idempotency / duplicate-handling contract for state-changing operations
`;
  return { name: "functional-surface.md", content };
}

function operationsDoc(codeMap: CodeMap): BootstrapDoc {
  const content = `${BANNER}# Operations Surface (As-Built)

> Operational *facts* (config, infra signals) are extracted from the scan. Operational
> *intent* (runbooks, SLOs, on-call) is **TODO** — none of it lives in application code.

## Configuration & Secrets

Environment variables referenced in code:

${codeMap.envVars.length > 0 ? codeMap.envVars.map((e) => `- \`${e}\``).join("\n") : "_none detected_"}

> **TODO:** mark which are secrets; document storage, rotation, and access policy.

## Infrastructure Signals

${codeMap.configSignals.length > 0 ? codeMap.configSignals.map((c) => `- ${c}`).join("\n") : "_none detected_"}

## TODO (human intent)

- [ ] Runbooks for each external dependency and failure mode
- [ ] Alerting rules aligned to SLO targets
- [ ] Background-job schedules, idempotency, and dead-letter/monitoring
- [ ] Deployment and rollback procedures
`;
  return { name: "operations-surface.md", content };
}

function docTodosDoc(gaps: DocumentationGap[], signals: string[]): BootstrapDoc {
  const byCategory = new Map<string, DocumentationGap[]>();
  for (const g of gaps) {
    const list = byCategory.get(g.category) ?? [];
    list.push(g);
    byCategory.set(g.category, list);
  }

  const sections = [...byCategory.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([category, items]) => {
      const rows = items
        .map(
          (g) =>
            `- [ ] **${g.name}** (${g.severity}) — _triggered by: ${g.triggeredBy.join(", ") || "—"}_\n` +
            `      ${g.whatToDocument}`,
        )
        .join("\n");
      return `### ${category}\n\n${rows}`;
    })
    .join("\n\n");

  const content = `${BANNER}# Documentation TODOs (Gap Inventory)

Detected signals: ${signals.map((s) => `\`${s}\``).join(", ") || "_none_"}

Each item below is a concern that **applies to your codebase** (based on the detected
signals) but has **no authored documentation**. Fill these in across the scaffold docs,
then run \`doc-lint\` in **doc-first** or **reconcile** mode to validate them.

> This is the on-ramp: \`bootstrap\` cannot author intent for you. It tells you exactly
> what a human needs to write to make the linter meaningful.

${sections || "_No concerns matched the detected signals._"}
`;
  return { name: "doc-todos.md", content };
}

// build the full evidence-named scaffold set + the gap inventory. deterministic.
export function buildBootstrapDocs(
  codeMap: CodeMap,
  signals: string[],
  matched: LoadedConcern[],
): BootstrapDoc[] {
  const gaps = computeDocumentationGaps(matched, signals);
  return [
    architectureDoc(codeMap),
    functionalDoc(codeMap),
    operationsDoc(codeMap),
    docTodosDoc(gaps, signals),
  ];
}

// write scaffolds under outDir, refusing to escape the project (path-traversal guard).
export function writeBootstrapDocs(
  docs: BootstrapDoc[],
  projectPath: string,
  outDir: string,
): string[] {
  const projectRoot = path.resolve(projectPath);
  const targetDir = path.resolve(projectRoot, outDir);
  const rel = path.relative(projectRoot, targetDir);
  if (rel.startsWith("..") || path.isAbsolute(rel)) {
    throw new Error(
      `bootstrap output must resolve to a directory inside the project; refusing to write to '${targetDir}'`,
    );
  }

  fs.mkdirSync(targetDir, { recursive: true });
  const written: string[] = [];
  for (const doc of docs) {
    const filePath = path.join(targetDir, doc.name);
    fs.writeFileSync(filePath, doc.content, "utf8");
    written.push(filePath);
  }
  return written;
}
