# =============================================================================
# CONCERN: Secrets Management
# =============================================================================
# This concern validates that every secret, credential, and cryptographic key
# referenced in the system documentation has a documented storage mechanism,
# rotation policy, and access control strategy. Undocumented secrets handling
# is one of the most common sources of security breaches.
#
# WHY THIS MATTERS:
# Secrets are the keys to the kingdom. API keys, database credentials,
# encryption keys, TLS certificates, and OAuth secrets grant access to
# critical system resources. When secrets handling is undocumented, teams
# default to insecure practices: hardcoded values in source code, shared
# credentials in environment variables without rotation, encryption keys
# without lifecycle management. A single leaked secret with no rotation
# policy means indefinite unauthorized access. Documented secrets management
# ensures the team has reasoned about storage, rotation, access control,
# and breach response for every credential in the system.
#
# TYPICAL MANIFESTATION:
# - ADD references "Stripe API key" but no documentation of where it's stored
# - Database connection strings mentioned but no credential rotation policy
# - Encryption at rest described but no key management or rotation strategy
# - TLS certificates used but no renewal/rotation documentation
# - OAuth client secrets referenced but no access control on who can read them
# =============================================================================

concern:
  id: "secrets-management"
  version: "1.0"
  name: "Secrets Management"
  category: "security"
  severity: "error"

  description: |
    Every secret, credential, and cryptographic key referenced in the system
    documentation must have documented handling policies covering: (1) where
    the secret is stored (vault, environment variable, KMS, config file),
    (2) how and when it is rotated (automatic, manual, cadence, dual-secret
    support during rotation), and (3) who or what can access it (IAM policies,
    service accounts, least-privilege scoping). Secrets without documented
    lifecycle management represent ticking time bombs - a single compromise
    with no rotation policy means indefinite unauthorized access.

# -----------------------------------------------------------------------------
# TRIGGERS: When to load this concern
# -----------------------------------------------------------------------------
triggers:
  any_of:
    - secrets
    - credentials
    - api-keys
    - encryption
    - certificates

  escalate_if:
    - payments           # payment gateway secrets enable financial fraud
    - pii                # encryption keys protecting PII must have strict lifecycle
    - multi-tenant       # tenant-specific secrets need isolation guarantees

# -----------------------------------------------------------------------------
# EVALUATION: The reasoning task
# -----------------------------------------------------------------------------
evaluation:
  question: |
    Systematically identify every secret, credential, and cryptographic key
    referenced in the system documentation, then evaluate whether each has
    documented storage, rotation, and access control policies.

    STEP 1: IDENTIFY ALL SECRETS AND CREDENTIALS
    Scan the ADD and FRD for references to secrets, credentials, and keys:

    a) API Keys and Tokens
       - Third-party API keys (Stripe, SendGrid, Twilio, AWS, etc.)
       - Internal service-to-service tokens
       - Webhook signing secrets
       - Look for: API key, token, secret key, signing key, webhook secret

    b) Database Credentials
       - Database connection strings with embedded credentials
       - Database user passwords
       - Redis/cache authentication tokens
       - Look for: connection string, DB password, database credentials, DSN

    c) Encryption Keys
       - Symmetric encryption keys (AES keys for data at rest)
       - Asymmetric key pairs (RSA/EC for signing, key exchange)
       - Key encryption keys (KEKs for envelope encryption)
       - Look for: encryption key, AES, RSA, KMS, key management, at-rest encryption

    d) TLS/SSL Certificates
       - Server certificates for HTTPS endpoints
       - Client certificates for mTLS
       - CA certificates for certificate pinning
       - Look for: TLS, SSL, certificate, cert, X.509, mTLS, HTTPS

    e) OAuth/OIDC Secrets
       - OAuth client secrets
       - OIDC provider configuration secrets
       - JWT signing keys (HMAC secrets or RSA private keys)
       - Look for: client secret, OAuth, OIDC, JWT secret, signing key

    f) Infrastructure Secrets
       - Cloud provider credentials (AWS access keys, GCP service account keys)
       - Container registry credentials
       - CI/CD pipeline secrets
       - SSH keys for deployment
       - Look for: AWS key, service account, deploy key, SSH key, registry credential

    STEP 2: FOR EACH SECRET, CHECK STORAGE MECHANISM
    Determine whether the documentation specifies WHERE the secret is stored:

    a) Acceptable Storage Mechanisms
       - Secrets vault (HashiCorp Vault, AWS Secrets Manager, Azure Key Vault,
         GCP Secret Manager)
       - Hardware Security Module (HSM) for cryptographic keys
       - KMS (Key Management Service) for envelope encryption
       - Encrypted environment variables with documented encryption method

    b) Unacceptable or Risky Storage
       - Hardcoded in source code
       - Plain-text configuration files committed to version control
       - Unencrypted environment variables without access control
       - Shared documents or wikis
       - No documentation at all (unknown storage)

    STEP 3: FOR EACH SECRET, CHECK ROTATION POLICY
    Determine whether the documentation specifies HOW and WHEN the secret
    is rotated:

    a) Rotation Cadence
       - How often is the secret rotated? (30 days, 90 days, annually)
       - Is rotation automatic or manual?
       - What triggers an emergency rotation? (suspected compromise)

    b) Rotation Mechanism
       - How is rotation performed without downtime? (dual-secret support,
         grace period, gradual rollout)
       - Are dependent systems notified of rotation?
       - Is there a rollback procedure if rotation causes issues?

    c) Key-Specific Lifecycle
       - For encryption keys: What is the cryptoperiod?
       - For certificates: When do they expire? Is renewal automated?
       - For API keys: Can old keys be revoked after rotation?

    STEP 4: FOR EACH SECRET, CHECK ACCESS CONTROL
    Determine whether the documentation specifies WHO or WHAT can access
    the secret:

    a) Service-Level Access
       - Which services or components need access to this secret?
       - Is access scoped to only the services that need it (least privilege)?
       - Are there separate credentials per service vs. shared credentials?

    b) Human Access
       - Which team members or roles can access the secret?
       - Is human access audited?
       - Are there break-glass procedures for emergency access?

    c) Access Auditing
       - Is access to secrets logged?
       - Are there alerts for unusual access patterns?

    STEP 5: ASSESS COMPLETENESS AND FLAG GAPS
    For each identified secret, classify its documentation as:
    - COMPLETE: Storage, rotation, and access control all documented
    - PARTIAL: Some aspects documented but gaps remain
    - ABSENT: Secret is referenced but no management documentation exists

  checklist:
    - id: "secrets-inventory"
      question: "Are all secrets and credentials referenced in the documentation inventoried?"
    - id: "storage-mechanism"
      question: "Does each secret have a documented storage mechanism (vault, KMS, HSM)?"
    - id: "rotation-policy"
      question: "Does each secret have a documented rotation policy with cadence and mechanism?"
    - id: "access-control"
      question: "Is access to each secret scoped to only the services and roles that need it?"
    - id: "encryption-key-lifecycle"
      question: "Do encryption keys have documented cryptoperiods and key rotation strategies?"
    - id: "certificate-renewal"
      question: "Do TLS certificates have documented expiration dates and renewal procedures?"

  evidence_required:
    - field: "secret_name"
      type: "string"
      description: "Identifier for the secret (e.g., 'Stripe API Secret Key', 'OrderDB Connection Password', 'User Data AES-256 Encryption Key')"
      required: true

    - field: "secret_type"
      type: "enum"
      values:
        - "api-key"
        - "db-credential"
        - "encryption-key"
        - "tls-certificate"
        - "oauth-secret"
        - "other"
      description: "Classification of the secret"
      required: true

    - field: "secret_source"
      type: "string"
      description: "Where the secret is referenced in documentation (e.g., 'ADD Section 3.4, Payment Integration', 'ADD Section 6.1, Database Configuration')"
      required: true

    - field: "storage_documented"
      type: "boolean"
      description: "Is the storage mechanism for this secret documented?"
      required: true

    - field: "storage_mechanism"
      type: "string | null"
      description: "How the secret is stored (e.g., 'AWS Secrets Manager in us-east-1', 'HashiCorp Vault at /secret/payments/stripe', 'Environment variable injected by Kubernetes secret'). Null if not documented."
      required: true

    - field: "rotation_documented"
      type: "boolean"
      description: "Is a rotation policy documented for this secret?"
      required: true

    - field: "rotation_policy"
      type: "string | null"
      description: "Rotation policy details (e.g., 'Automatic 90-day rotation via AWS Secrets Manager, dual-secret support during 24h rotation window'). Null if not documented."
      required: true

    - field: "access_control_documented"
      type: "boolean"
      description: "Is access control documented for this secret?"
      required: true

    - field: "confidence"
      type: "enum"
      values: ["high", "medium", "low"]
      description: "Your confidence that this assessment is accurate based on available documentation"
      required: true

  failure_condition: |
    Report as ERROR when ANY of the following are true:

    1. storage_documented is FALSE for any secret - a secret with unknown
       storage location cannot be managed, rotated, or audited. It may be
       hardcoded in source code or stored insecurely.

    2. secret_type is "encryption-key" and rotation_documented is FALSE -
       encryption keys without a rotation policy mean that a single key
       compromise exposes ALL data ever encrypted with that key, with no
       mechanism to limit the blast radius.

    3. secret_type is "tls-certificate" and rotation_documented is FALSE -
       certificates expire, and unplanned expiry causes outages. Renewal
       must be documented and ideally automated.

    4. storage_mechanism indicates an insecure practice (hardcoded in source,
       plain-text config file, committed to version control).

    5. secret_type is "db-credential" or "api-key" for a payment or PII
       system and access_control_documented is FALSE - secrets protecting
       financial or personal data must have documented access restrictions.

    Report as WARNING when:

    1. rotation_documented is FALSE for non-critical secrets (e.g., internal
       service tokens for non-sensitive systems) - rotation is best practice
       but lower severity for non-critical credentials.

    2. access_control_documented is FALSE for infrastructure secrets that
       don't directly protect PII or financial data.

    3. rotation_policy is documented but does not include a mechanism for
       zero-downtime rotation (no dual-secret support or grace period).

    4. storage_documented is TRUE but storage_mechanism is "environment
       variable" without further detail on how the variable is secured
       (encrypted at rest, access controlled, not logged).

    5. Secret is referenced in multiple documents with inconsistent handling
       descriptions (e.g., ADD says Vault, FRD says environment variable).

  recommendation_template: |
    ## Gap: Undocumented Secrets Handling - {secret_name}

    **Secret Type:** {secret_type}
    **Source:** {secret_source}
    **Storage Documented:** {storage_documented}
    **Rotation Documented:** {rotation_documented}
    **Access Control Documented:** {access_control_documented}

    ### Required Documentation

    Add secrets management documentation covering:

    1. **Storage**
       - Where is this secret stored? (vault path, KMS key ID, secrets manager ARN)
       - How is it injected into the application? (environment variable, sidecar,
         init container, SDK call)
       - Example: "Stored in AWS Secrets Manager at arn:aws:secretsmanager:us-east-1:
         123456:secret/payments/stripe-api-key. Injected via ECS task definition
         as environment variable STRIPE_SECRET_KEY."

    2. **Rotation**
       - How often is this secret rotated? (cadence)
       - How is rotation performed? (automatic via secrets manager, manual runbook)
       - How is downtime avoided during rotation? (dual-secret support, grace period)
       - Example: "Rotated every 90 days via AWS Secrets Manager automatic rotation.
         Lambda function generates new key, updates Stripe dashboard, and stores new
         value. Previous key remains valid for 24 hours (Stripe supports dual keys)."

    3. **Access Control**
       - Which services/roles can read this secret?
       - Is access logged and auditable?
       - Example: "Only the PaymentService ECS task role (arn:aws:iam::123456:role/
         payment-service) can read this secret. Access logged in CloudTrail.
         Alert on access from any other principal."

    4. **Breach Response**
       - What is the procedure if this secret is compromised?
       - How quickly can it be rotated in an emergency?
       - What systems need to be notified?

# -----------------------------------------------------------------------------
# EXAMPLES
# -----------------------------------------------------------------------------
examples:
  well_documented:
    - source: "ADD Section 8 - Secrets Management"
      text: |
        "Stripe API Secret Key:
        - Storage: AWS Secrets Manager (arn:aws:secretsmanager:us-east-1:
          123456789:secret/production/stripe-api-key)
        - Injection: ECS task definition references secret ARN; injected as
          STRIPE_SECRET_KEY environment variable at container start
        - Rotation: Automatic 90-day rotation via Lambda function. Function
          generates new restricted key via Stripe API, stores in Secrets Manager,
          and revokes old key after 24-hour grace period.
        - Access: Only payment-service IAM role can GetSecretValue. CloudTrail
          logs all access. PagerDuty alert for access from unexpected principals.
        - Breach procedure: Emergency rotation runbook in Confluence. Can rotate
          in under 5 minutes. Stripe dashboard allows immediate key revocation."
      assessment: |
        secret_name: "Stripe API Secret Key"
        secret_type: "api-key"
        storage_documented: true
        storage_mechanism: "AWS Secrets Manager"
        rotation_documented: true
        rotation_policy: "Automatic 90-day rotation, 24-hour dual-key grace period"
        access_control_documented: true
        confidence: "high"

  poorly_documented:
    - source: "ADD Section 4.3"
      text: |
        "The PaymentService connects to Stripe using the API secret key.
        The database connection uses a username and password for authentication.
        All sensitive data is encrypted using AES-256."
      assessment: |
        secret_name: "Stripe API Secret Key"
        secret_type: "api-key"
        storage_documented: false
        storage_mechanism: null
        rotation_documented: false
        rotation_policy: null
        access_control_documented: false
        gap: "Three secrets referenced (Stripe API key, DB credentials, AES-256 key)
              but none have documented storage, rotation, or access control. Where are
              they stored? How are they rotated? Who can access them? These questions
              are unanswered, leaving the secrets management posture completely opaque."
        confidence: "high"

# -----------------------------------------------------------------------------
# METADATA
# -----------------------------------------------------------------------------
metadata:
  created: "2026-02"
  last_updated: "2026-02"
  author: "doc-lint v0.2"
  related_concerns:
    - "threat-model-coverage"        # credential stores are attack surfaces needing threat models
    - "auth-boundary-consistency"    # auth tokens and API keys are secrets that need management
    - "input-validation"             # credentials arriving as input need validation
  references:
    - "OWASP Secrets Management Cheat Sheet: https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html"
    - "NIST SP 800-57: Recommendation for Key Management"
    - "CIS Benchmark: Secrets Management Controls"
    - "HashiCorp Vault Best Practices: https://developer.hashicorp.com/vault/docs/concepts/lease"
